<a href="https://colab.research.google.com/github/leresearth/laras.dibimbing.github.io/blob/main/Chafda_Larasati_Assignment_Day_5_Intermediate_Data_Types_and_Structures_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Poin Assignment :
**1.** Lakukan investigasi pada kondisi berikut :
- 1a. Lakukan pengecekan pada kolom mana yang terdapat data continue di dataframe ? (20 poin)
- 1b. Lakukan pengecekan pada kolom mana yang terdapat jenis kategorikal serta Uraikan juga jenis kategorikalnya termasuk kategorikal apa di masing-masing kolom dataframe ? (20 poin)

**2.** Looping
- `for` loop : print semua nama kolom yang ada pada file `titanic.xlsx` yang hanya dimulai dengan huruf konsonan (15 poin)
- `while` loop : print semua angka ganjil hingga `30`. Jika angka ganjil habis dibagi 3, print `"angka ini habis dibagi 3"` (15 poin)

**3** Lakukan manipulasi data `titanic.xlsx` menggunakan `lambda function` sesuai perintah dibawah ini :
1. Hitung jumlah missing value (NaN) pada kolom `body` (15)
2. Ubah female menjadi `0` dan male menjadi `1` pada kolom `sex` (15)

### Note : soal 1,2,3 menggunakan file titanic.csv

In [2]:
!ls /content/drive

ls: cannot access '/content/drive': No such file or directory

In [3]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [4]:
import pandas as pd
# Assuming the file is in the root of your Google Drive
df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Assignment Day 5/titanic.xlsx')

In [5]:
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [6]:
# prompt: Using dataframe df: data continu

import altair as alt

# Filter the DataFrame to include only rows where 'survived' is 1
df_survived = df[df['survived'] == 1]

# Create a scatter plot of 'fare' vs 'age' for the survived passengers
chart = alt.Chart(df_survived).mark_point().encode(
    x='age',
    y='fare'
).properties(
    title='Fare vs Age for Survived Passengers'
)

# Display the chart
chart

alt.Chart(...)

1. Lakukan investigasi pada kondisi berikut :

    1a. Lakukan pengecekan pada kolom mana yang terdapat data continue di dataframe ? (20 poin)
    1b. Lakukan pengecekan pada kolom mana yang terdapat jenis kategorikal serta Uraikan juga jenis kategorikalnya termasuk kategorikal apa di masing-masing kolom dataframe ? (20 poin)

In [16]:
#1a
data_continue = []
for col in df.columns:
  if df[col].dtype in ['float64']:
    data_continue.append(col)

print('Kolom berupa data continue:', data_continue)

#1b
data_kategorik = []
for col in df.columns:
  if df[col].dtype == 'object':
    data_kategorik.append(col)

data_kategorik.extend(['pclass', 'survived'])

print(f'Kolom kategorikal (tipe object/teks):{data_kategorik}')

jenis_kategorik = {
    'name': 'nominal',
    'sex': 'nominal',
     'ticket': 'nominal',
     'cabin': 'nominal',
     'embarked': 'nominal',
     'boat': 'nominal',
     'home.dest': 'nominal',
     'pclass': 'ordinal',
     'survived': 'nominal',
}

print(f'Jenis kategorikal: {jenis_kategorik}')

Kolom berupa data continue: ['age', 'fare', 'body']
Kolom kategorikal (tipe object/teks):['name', 'sex', 'ticket', 'cabin', 'embarked', 'boat', 'home.dest', 'pclass', 'survived']
Jenis kategorikal: {'name': 'nominal', 'sex': 'nominal', 'ticket': 'nominal', 'cabin': 'nominal', 'embarked': 'nominal', 'boat': 'nominal', 'home.dest': 'nominal', 'pclass': 'ordinal', 'survived': 'nominal'}

In [17]:
# 2a. for loop
# Kolom yang dimulai dengan huruf konsonan
vokal = ['a', 'i', 'u', 'e', 'o']

# Looping kolom
for col in df.columns:
  huruf_konsonan = col[0]


    # Cek apakah huruf pertama adalah alfabet dan bukan huruf vokal
  if huruf_konsonan not in vokal:
    print(col)

pclass
survived
name
sex
sibsp
parch
ticket
fare
cabin
boat
body
home.dest

In [18]:
# 2b. while loop
# Print semua angka ganjil hingga 30 yang habis dibagi 3
i = 1
while i <= 30:
  if i % 2 == 1:
    if i % 3 == 0:
      print(f'{i} adalah angka ganjil di bawah 30 yang habis dibagi 3')
  i += 1

3 adalah angka ganjil di bawah 30 yang habis dibagi 3
9 adalah angka ganjil di bawah 30 yang habis dibagi 3
15 adalah angka ganjil di bawah 30 yang habis dibagi 3
21 adalah angka ganjil di bawah 30 yang habis dibagi 3
27 adalah angka ganjil di bawah 30 yang habis dibagi 3

In [19]:
# 3a. Hitung jumlah missing value (NaN) pada kolom body

# Menggunakan .apply() dengan lambda function pada kolom 'body'
# pd.isna(x) akan mengembalikan True jika nilai x adalah NaN
# .sum() akan menjumlahkan semua nilai True (True=1, False=0)
if 'body' in df.columns:
  missing_value_body = df['body'].apply(lambda x:1 if pd.isna(x) else 0).sum()
  print(f'Jumlah missing value pada kolom body sejumlah {missing_value_body}')

Jumlah missing value pada kolom body sejumlah 1220

In [20]:
# Ubah female jadi 0 dan male 1
if 'sex' in df.columns:
  df['sex'] = df['sex'].apply(lambda x: 0 if x == 'female' else x)
  df['sex'] = df['sex'].apply(lambda x: 1 if x == 'male' else x)
  print (df['sex'])

0       0
1       1
2       0
3       1
4       0
       ..
1344    0
1345    0
1346    1
1347    1
1348    1
Name: sex, Length: 1349, dtype: int64

In [ ]:
!ls /content/drive/MyDrive/

After verifying the file exists at `/content/drive/MyDrive/titanic.csv`, you can run the following cell again to load the data:

In [108]:
import pandas as pd
# Assuming the file is in the root of your Google Drive
df = pd.read_csv